apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-recommendation
  template:
    metadata:
      labels:
        app: mongodb-recommendation
    spec:
      containers:
        - name: mongodb-recommendation
          image: 172.17.137.2/ns-mapdemo-1/mongo:3.6.9
#          image: mongo:latest
          envFrom:
            - secretRef:
                name: mongodb-server-credentials
          ports:
            - containerPort: 27018
          resources:
            limits:
              memory: 300Mi
      imagePullSecrets:
        - name: ns-mapdemo-1-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-recommendation
spec:
  selector:
    app: mongodb-recommendation
  type: LoadBalancer
  ports:
    - port: 27018
      targetPort: 27017
