apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: 172.17.137.2/ns-mapdemo-1/rabbitmq:3.7.8-management
          envFrom:
            - secretRef:
                name: rabbitmq-server-credentials
          ports:
            - containerPort: 5671
            - containerPort: 5672
            - containerPort: 15672
          resources:
            limits:
              memory: 300Mi
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: "/api/aliveness-test/%2F"
              port: 15672
              httpHeaders:
                - name: Authorization
                  value: Basic Z3Vlc3Q6Z3Vlc3Q=
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 20
            failureThreshold: 30
      imagePullSecrets:
        - name: ns-mapdemo-1-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports:
    - name: tcp-secure
      port: 5671
    - name: tcp-not-secure
      port: 5672
    - name: http-mgm-ui
      port: 15672
