apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-recommendation
  template:
    metadata:
      labels:
        app: mongodb-recommendation
    spec:
      containers:
        - name: mongodb-recommendation
          image: mongo:3.6.9
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-recommendation
spec:
  selector:
    app: mongodb-recommendation
  ports:
    - port: 27018
      targetPort: 27017
