apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-cluster-users
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: sso:devuser1@pacific.local
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: sso:devuser2@pacific.local
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: sso:devuser3@pacific.local
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: sso:opsuser1@pacific.local
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: sso:opsuser2@pacific.local
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: sso:opsuser3@pacific.local
  apiGroup: rbac.authorization.k8s.io

