apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: pacific-tkc-dev-cluster1
  namespace: ns-mapdemo-1
spec:
  distribution:
    version: v1.16
  topology:
    controlPlane:
      count: 1
      class: best-effort-large
      storageClass: pacific-storage-policy
    workers:
      count: 2
      class: best-effort-large
      storageClass: pacific-storage-policy
    settings:
      network:
        cni:
          name: calico
        services:
          cidrBlocks: ["198.51.100.0/12"]
        pods:
          cidrBlocks: ["192.0.2.0/16"]
