apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
spec:
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
        version: v1
    spec:
      containers:
        - name: recommendation
          image: 172.17.137.2/ns-mapdemo-1/microservice-demo/recommendation-service:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,prod"
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "400Mi"
      imagePullSecrets:
#        - name: microservice-demo-image-pull-secret
        - name: microservice-demo-registry-secret