server.port: 7003

# 本番環境では "none" を設定
spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/review-db?character_set_server=utf8mb4
  username: vmware
  password: password
  sql-script-encoding: utf-8
  hikari:
    initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    jp.vmware.sol: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.profiles: docker

spring.datasource:
  url: jdbc:mysql://mysql/review-db?character_set_server=utf8mb4

server.port: 8080
