apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
spec:
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
        version: v1
    spec:
      containers:
        - name: review
          image: microservice-demo/review-service:v1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,prod"
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "400Mi"